name: food_ordering_app_with_flutter_and_bloc
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core:
    path: packages/core
  google_maps_flutter: ^2.5.3
  go_router: ^13.0.1
  google_fonts: ^4.0.4  # Downgrade to a version compatible with http ^0.13.4
  flutter_bloc: ^8.1.3
  uuid: ^4.3.3
  envied: ^0.5.3
  flutter_launcher_icons: ^0.13.1
  equatable: ^2.0.5
  flutter_login: ^5.0.0
  qr_code_scanner: ^1.0.0
  http: ^0.13.4
  local_auth: ^2.2.0
  firebase_core: ^3.1.1
  image_picker: ^1.1.2
  firebase_database: ^11.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  envied_generator: ^0.5.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/copi.png"
